config/routes.rb
GestionCe::Application.routes.draw do
	get 'login' => 'site#login'
	post 'login' => 'site#auth'
	get 'logout' => 'site#logout'

	get 'admin' => 'site#admin'
	get 'report' => 'site#report'
	get 'balance' => 'site#balance'

	resources :users
	resources :years
	resources :agencies
	resources :activities do
		member do
			get :close
		end
	end
	resources :entries
	resources :payments

	root to: 'site#index'
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :budget
	has_one :year, through: :budget
	has_one :account, through: :budget
	validates_presence_of :amount, :budget, :date
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	def index
		@year = Year.find_by_year params[:year]
	end

	def new
		params[:date] = Date.today
	end

	def create
		p params
		params[:date] = Date.parse params[:date]
		year = Year.find params[:year]
		Account.all.each do |account|
			amount = params[account.tag]
			if amount && !amount.empty?
				budget = Budget.get year, account
				budget.payments.create! amount: amount, date: params[:date]
			end
		end
		redirect_to action: :index, year: year
	rescue Exception => e
		flash[:error] = e.message
		render :new
	end

	def edit
		@payment = Payment.find params[:id]
	end

	def update
		year = Year.find params[:year]
		account = Account.find params[:account]
		budget = Budget.get year, account
		params[:payment][:budget_id] = budget.id
		@payment = Payment.find params[:id]
		@payment.update! params.require(:payment).permit(:date, :amount, :budget_id)
		redirect_to action: :index, year: @payment.year
	rescue Exception => e
		flash[:error] = e.message
		render :edit
	end

	def destroy
		payment = Payment.find(params[:id]).destroy!
	rescue Exception => e
		flash[:error] = e.message
	ensure
		redirect_to :admin
	end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/edit.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<%= form_for @payment, builder: BootstrapFormHorizontalBuilder, html: { class: %w(form-horizontal well span6) } do |f| %>
			<%= field_set_tag t("form.#{controller.controller_name}.#{controller.action_name}"), class: %w(compact) do %>
				<%= f.text_field :date, value: l(f.object.date), required: true,  class: %w(datepicker) %>
				<%= f.amount_field :amount, value: f.object.amount, required: true %>
				<%= select_label_tag :account, options_for_select(Account.all.collect { |a| [a.name, a.id] }, f.object.budget.account.id) %>
				<%= select_label_tag :year, options_for_select(Year.all.collect { |y| [y.year, y.id] }, f.object.budget.year.id) %>
			<% end %>
			<%= submit_tag t("form.#{controller.action_name}"), class: %(btn btn-primary pull-right) %>
		<% end %>
	</div>
</div>

app/views/payments/index.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">
			<h3><%= t 'Payments for {year}', year: @year.year %></h3>
			<table class="table table-bordered">
				<thead>
				<tr>
					<th>
						<%= link_to new_payment_path do
							image_tag 'empty.png', alt: t('Create payment'), class: 'sprite-silk-money_add'
						end %>
					</th>
					<th><%=  t 'Date' %></th>
					<th><%=  t 'Account' %></th>
					<th><%=  t 'Amount' %></th>
				</tr>
				</thead>
				<tbody>
				<% @year.payments.sort_by(&:date).each do |payment| %>
					<tr>
						<td>
							<%= link_to [:edit, payment] do
								image_tag 'empty.png', title: t('Edit payment'), class: 'sprite-silk-money'
							end %>
							<%= link_to payment, method: :delete, data: { confirm: t('Are you sure you want to delete this payment ?') } do
								image_tag 'empty.png', title: t('Delete payment'), class: 'sprite-silk-money_delete'
							end %>
						</td>
						<td><%= l payment.date %></td>
						<td><%= payment.budget.account.name %></td>
						<td><%= number_to_currency payment.amount %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>

app/views/payments/new.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<%= form_tag payments_path, class: %w(form-horizontal well span6) do %>
			<%= field_set_tag t("form.#{controller.controller_name}.#{controller.action_name}"), class: %w(compact) do %>
				<%= text_field_label_tag :date, l(params[:date]), required: true,  class: %w(datepicker) %>
				<% Account.all.each do |account| %>
					<%= amount_field_label_tag account.tag, params[account.tag] %>
				<% end %>
				<%= select_label_tag :year, options_for_select(Year.all.collect { |y| [y.year, y.id] }, Year.current.id) %>
			<% end %>
			<%= submit_tag t("form.#{controller.action_name}"), class: %(btn btn-primary pull-right) %>
		<% end %>
	</div>
</div>