config/routes.rb
GestionCe::Application.routes.draw do
	get 'login' => 'site#login'
	post 'login' => 'site#auth'
	get 'logout' => 'site#logout'

	get 'admin' => 'site#admin'
	get 'report' => 'site#report'
	get 'balance' => 'site#balance'

	resources :users
	resources :years
	resources :agencies
	resources :activities do
		member do
			get :close
		end
	end
	resources :entries
	resources :payments

	root to: 'site#index'
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	skip_before_filter :require_login, only: [:login, :auth]

	def index
		@year = self.year
	end

	def login
	end

	def auth
		username = params[:username]
		password = params[:password]
		@me = User.where(login: username, password: User.hash_password(password)).first!
		session[:me] = @me.id
		flash[:success] = t 'Welcome {user}', user: @me.surname
		redirect_to root_path
	rescue
		flash[:error] = t 'Authentication failure'
		redirect_to :login
	end

	def logout
		session.clear
		redirect_to root_path
	end

	def admin
	end

	def balance
		@year = self.year
	end
end

app/helpers/site_helper.rb
module SiteHelper
	def agency_progress_bar agency, budget
		progress_bar agency.percentage(budget), 25, 50
	end

	def budget_progress_bar budget
		progress_bar budget.percentage, 25, 50
	end
end

app/views/site/_budget.html.erb
<% account, year = budget.account, budget.year %>
<h3><%= account.name %> <%= year.year %></h3>
<table class="table table-bordered table-condensed">
	<thead>
	<tr>
		<th></th>
		<th><%= t 'Agency' %></th>
		<th><%= t 'Workforce' %></th>
		<th><%= t 'Budget' %></th>
		<th><%= t 'Used' %></th>
		<th><%= t 'Remaining' %></th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	<% year.agencies.each do |agency| %>
		<tr>
			<th>
				<%= link_to activities_path(agency: agency, year: year) do
					image_tag 'empty.png', title: t('Show'), class: 'sprite-silk-magnifier'
				end %>
			</th>
			<th><%= agency.name %></th>
			<td><%= agency.employees year %></td>
			<td><%= number_to_currency agency.available budget %></td>
			<td><%= number_to_currency agency.used budget %></td>
			<% remaining = agency.remaining budget %>
			<%= content_tag :td, number_to_currency(remaining), class: remaining >= 0 ? 'alert-success' : 'alert-error' %>
			<td>
				<%= agency_progress_bar agency, budget %>
			</td>
		</tr>
	<% end %>
	<tr>
		<th></th>
		<th><%= t 'Common' %></th>
		<td></td>
		<td><%= number_to_currency budget.common_credit %></td>
		<td><%= number_to_currency budget.common_debit %></td>
		<td><%= number_to_currency budget.common %></td>
		<td></td>
	</tr>
	</tbody>
	<tfoot>
	<tr>
		<th></th>
		<th>Total</th>
		<td><%= budget.year.employees %></td>
		<td><%= number_to_currency budget.available %></td>
		<td><%= number_to_currency budget.used %></td>
		<%= content_tag :td, number_to_currency(budget.remaining), class: budget.remaining >= 0 ? 'alert-success' : 'alert-error' %>
		<td>
			<%= budget_progress_bar budget %>
		</td>
	</tr>
	</tfoot>
</table>

app/views/site/_modal_activity.html.erb
<div id="modal-activity" class="modal hide fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3><%= t 'Create activity' %></h3>
	</div>
	<%= form_for Activity.new(date: Date.today), builder: BootstrapFormHorizontalBuilder, html: { class: %w(form-horizontal) } do |f| %>
		<div class="modal-body">
			<%= f.text_field :description, placeholder: t('Name'), required: true %>
			<%= f.text_field :date, required: true, type: :date, value: l(f.object.date), class: :datepicker %>
			<%= f.text_field :plan_debit, type: :number, required: true %>
			<%= f.text_field :plan_credit, type: :number, required: true %>
			<%= f.select :agency_id, options_for_select(Agency.all.collect { |a| [a.name, a.id] }, @me.agency.id), include_blank: true %>
			<%= f.select :year_id, options_for_select(Year.all.collect { |y| [y.year, y.id] }, Year.current.id), include_blank: true %>
		</div>
		<div class="modal-footer">
			<%= f.submit t('Create'), class: %w(btn btn-primary) %>
			<button class="btn btn-danger" data-dismiss="modal" aria-hidden="true"><%= t 'Close' %></button>
		</div>
	<% end %>
</div>

app/views/site/_modal_agency.html.erb
<div id="modal-agency" class="modal hide fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3><%= t 'Create agency' %></h3>
	</div>
	<%= form_for Agency.new, builder: BootstrapFormPrependBuilder do |f| %>
		<div class="modal-body">
			<%= f.text_field_prepend 'icon-home', :name, placeholder: t('Name'), required: true %>
		</div>
		<div class="modal-footer">
			<%= f.submit t('Create'), class: %w(btn btn-primary) %>
			<button class="btn btn-danger" data-dismiss="modal" aria-hidden="true"><%= t 'Close' %></button>
		</div>
	<% end %>
</div>

app/views/site/_modal_user.html.erb
<div id="modal-user" class="modal hide fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3><%= t 'Create user' %></h3>
	</div>
	<%= form_for User.new, builder: BootstrapFormPrependBuilder do |f| %>
		<div class="modal-body">
			<%= f.text_field_prepend 'icon-user', :name, placeholder: t('Name'), required: true %>
			<%= f.text_field_prepend 'icon-user', :surname, placeholder: t('Surname'), required: true %>
			<%= f.text_field_prepend 'icon-lock', :password, placeholder: t('Password'), required: true %>
			<%= f.select :agency, Agency.all.collect { |a| [a.name, a.id] } %>
		</div>
		<div class="modal-footer">
			<%= f.submit t('Create'), class: %w(btn btn-primary) %>
			<button class="btn btn-danger" data-dismiss="modal" aria-hidden="true"><%= t 'Close' %></button>
		</div>
	<% end %>
</div>

app/views/site/admin.html.erb
<%= render 'modal_agency' %>
<%= render 'modal_user' %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">
			<h3><%= t 'Budgets' %></h3>
			<table class="table table-bordered">
				<thead>
				<tr>
					<th>
						<%= link_to new_year_path do
							image_tag 'empty.png', alt: t('Create year'), class: 'sprite-silk-table_add'
						end %>
					</th>
					<th><%=  t 'Year' %></th>
					<th><%=  t 'Workforce' %></th>
					<% Account.all.each do |account| %>
						<th><%= account.name %></th>
					<% end %>
				</tr>
				</thead>
				<tbody>
				<% Year.order("year desc").limit(5).each do |year| %>
					<tr>
						<td>
							<%= link_to [:edit, year] do
								image_tag 'empty.png', title: t('Edit budget'), class: 'sprite-silk-table_edit'
							end %>
							<%= link_to year, method: :delete, data: { confirm: t('Are you sure you want to delete this budget ?') } do
								image_tag 'empty.png', title: t('Delete budget'), class: 'sprite-silk-table_delete'
							end %>
							<%= link_to payments_path(year: year) do
								image_tag 'empty.png', title: t('Payments'), class: 'sprite-silk-money'
							end %>
						</td>
						<th><%= year.year %></th>
						<td><%= number_with_delimiter year.employees %></td>
						<% Account.all.each do |account| %>
							<td><%= number_to_currency Budget.get(year, account).available %></td>
						<% end %>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>
		<div class="container-fluid span6">
			<div class="row-fluid">
				<div class="span">
					<h3><%= t 'Agencies' %></h3>
					<table class="table table-bordered">
						<thead>
							<tr>
								<td>
									<%= link_to '#modal-agency', role: :button, 'data-toggle' => :modal do
										image_tag 'empty.png', alt: t('Create agency'), class: 'sprite-silk-brick_add'
									end %>
								</td>
								<th><%= t 'Agency' %></th>
							</tr>
						</thead>
						<tbody>
							<% Agency.order(:name).each do |agency| %>
								<tr>
									<td>
										<%= link_to agency do
											image_tag 'empty.png', title: t('Edit agency'), class: 'sprite-silk-brick_edit'
										end %>
										<%= link_to agency, method: :delete, data: { confirm: t('Are you sure you want to delete this agency ?') } do
											image_tag 'empty.png', title: t('Delete agency'), class: 'sprite-silk-brick_delete'
										end %>
									</td>
									<td><%= agency.name %></td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span">
					<h3><%= t 'Users' %></h3>
					<table class="table table-bordered">
						<thead>
						<tr>
							<td>
								<%= link_to '#modal-user', role: :button, 'data-toggle' => :modal do
									image_tag 'empty.png', alt: t('Create user'), class: 'sprite-silk-user_add'
								end %>
							</td>
							<th><%= t 'Name' %></th>
							<th><%= t 'Agency' %></th>
						</tr>
						</thead>
						<tbody>
						<% User.order(:name).each do |user| %>
							<tr>
								<td>
									<%= link_to user do
										image_tag 'empty.png', title: t('Edit user'), class: 'sprite-silk-user_edit'
									end %>
									<%= link_to user, method: :delete, data: { confirm: t('Are you sure you want to delete this user ?') } do
										image_tag 'empty.png', title: t('Delete user'), class: 'sprite-silk-user_delete'
									end %>
								</td>
								<td><%= user.display_name %></td>
								<td><%= user.agency.name %></td>
							</tr>
						<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/site/balance.html.erb
<table class="table table-bordered table-condensed">
	<thead>
		<tr>
			<th><%= t 'Agency' %></th>
			<th><%= t 'Activity' %></th>
			<th><%= t 'To' %></th>
			<th><%= t 'Description' %></th>
			<th><%= t 'Date' %></th>
			<th><%= t 'Debit' %></th>
			<th><%= t 'Credit' %></th>
		</tr>
	</thead>
	<tbody>
		<% @year.entries.order(:date).each do |entry| %>
			<tr>
				<th><%= entry.agency.name unless entry.agency.nil? %></th>
				<th><%= entry.activity.description unless entry.activity.nil? %></th>
				<th><%= entry.to %></th>
				<td><%= entry.description %></td>
				<td><%= l entry.date %></td>
				<td class="alert-error"><%= entry.debit? ? number_to_currency(-entry.amount) : '' %></td>
				<td class="alert-success"><%= entry.credit? ? number_to_currency(entry.amount) : '' %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/site/index.html.erb
<%= render 'modal_activity' %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">
			<% Account.all.each do |account| %>
				<div class="row-fluid">
					<div class="span12">
						<%= render 'budget', budget: @year.budget(account) %>
					</div>
				</div>
			<% end %>
		</div>
		<div class="span6">
			<h3><%= t 'Activities' %></h3>
			<table class="table table-bordered table-striped table-condensed">
				<thead>
				<tr>
					<th>
						<%= link_to '#modal-activity', role: :button, 'data-toggle' => :modal do
							image_tag 'empty.png', alt: t('Create activity'), class: 'sprite-silk-date_add'
						end %>
						<%=
							link_to(url_for(params.merge all: !to_bool(:all))) do
							image_tag 'empty.png', title: t('Show all activities'), class: 'sprite-silk-date_magnify'
						end %>
					</th>
					<th><%= t('Agency') %></th>
					<th><%= t('Activity') %></th>
					<th><%= t('Date') %></th>
					<th><%= t('Budget') %></th>
				</tr>
				</thead>
				<tbody>
				<%
				   activities = Activity.where(year_id: @year, agency_id: @me.agency)
				   activities = activities.where(closed: false) unless to_bool :all
				   activities.order('date').each do |activity| %>
					<%= content_tag :tr, class: activity.closed? ? :closed : nil do %>
						<td>
							<%= link_to activity do
								image_tag 'empty.png', title: t('Show activity'), class: 'sprite-silk-date_go'
							end %>
							<% if activity.closed? %>
								<%= image_tag 'empty.png', title: t('Closed activity'), class: 'sprite-silk-lock' %>
							<% else %>
								<%= link_to activity, method: :delete, data: { confirm: t('Are you sure you want to delete this activity ?') } do
									image_tag 'empty.png', title: t('Delete activity'), class: 'sprite-silk-date_delete'
								end %>
							<% end %>
						</td>
						<td><%= activity.agency.name %></td>
						<td><%= activity.description %></td>
						<td><%= l activity.date %></td>
						<td><%= number_to_currency activity.total %></td>
					<% end
					   end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/site/login.html.erb
<div class="row">
	<%= form_tag login_path, class: %(login-form well span4 offset4) do %>
		<%= field_set_tag(t 'Sign in') {} %>
		<%= text_field_prepend_tag 'icon-user', :login_form_username, nil, name: :username, placeholder: t('Username') %>
		<%= password_field_prepend_tag :login_form_password, nil, name: :password, placeholder: t('Password'), required: true %>
		<%= submit_tag t('Sign in'), class: %(btn btn-primary pull-right) %>
	<% end %>
</div>