config/routes.rb
GestionCe::Application.routes.draw do
	get 'login' => 'site#login'
	post 'login' => 'site#auth'
	get 'logout' => 'site#logout'

	get 'admin' => 'site#admin'
	get 'report' => 'site#report'
	get 'balance' => 'site#balance'

	resources :users
	resources :years
	resources :agencies
	resources :activities do
		member do
			get :close
		end
	end
	resources :entries
	resources :payments

	root to: 'site#index'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :agency
	belongs_to :year
	has_many :entries, inverse_of: :activity, dependent: :nullify
	validates_presence_of :agency, :year

	before_validation do
		self.closed ||= false
		true
	end

	def self.find_open
		self.where closed: false
	end

	def find_open
		activities = Activity.find_open
		activities << self unless activities.include? self
		activities
	end

	def plan_total
		self.plan_credit - self.plan_debit
	end

	def plan_percentage
		self.plan_debit == 0 ? 0 : (1 - self.plan_credit / self.plan_debit) * 100
	end

	def debit
		-Entry.total(self.entries.select &:debit?)
	end

	def credit
		Entry.total self.entries.select &:credit?
	end

	def total
		Entry.total self.entries
	end

	def percentage
		self.debit == 0 ? 0 : (1 - self.credit / self.debit) * 100
	end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
        def index
                @year = params[:year].nil? ? Year.current : Year.find_by_year(params[:year])
                @agencies = params[:agency].nil? ? Agency.all : [Agency.find_by_tag(params[:agency])]
        end

        def create
                @activity = Activity.new params.require(:activity).permit(:description, :date, :plan_debit, :plan_credit, :agency_id, :year_id)
                @activity.save!
		redirect_to root_path
	rescue Exception => e
		flash[:error] = e.message
		render :new
	end

	def show
		@activity = Activity.find params[:id]
		@entry = Entry.new date: Date.today, activity: @activity, agency: @me.agency, budget: @activity.year.budget(:social)
	end

	def edit
		@activity = Activity.find params[:id]
		render :new
	end

	def update
		@activity = Activity.find params[:id]
		@activity.update! params.require(:activity).permit(:description, :date, :plan_debit, :plan_credit, :agency_id, :year_id)
		redirect_to root_path
	rescue Exception => e
		flash[:error] = e.message
		render :new
	end

	def close
		@activity = Activity.find params[:id]
		@activity.toggle! :closed
		redirect_to @activity
	end

	def destroy
		Activity.find(params[:id]).destroy!
	rescue Exception => e
		flash[:error] = e.message
	ensure
		redirect_to root_path
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
	def activity_progress_bar percentage
		progress_bar percentage, 50, 50, inverse: true
	end
end

app/views/activities/_entry.html.erb
<%= form_for @entry, builder: BootstrapFormHorizontalBuilder, html: { class: %w(form-horizontal form-compact well) } do |f| %>
	<%= field_set_tag t('New entry'), class: %w(compact) do %>
		<%= f.text_field :date, class: :datepicker, value: l(f.object.date), required: true %>
		<%= f.text_field :description, required: true %>
		<%= f.amount_field :amount, type: :number, required: true %>
		<%= f.select :category, Entry::CATEGORIES.collect { |c| [t(c), c] } %>
	<% end %>

	<%= field_set_tag t('Check'), class: %w(compact) do %>
		<%= f.text_field :number %>
		<%= f.text_field :bank %>
	<% end %>

	<%= field_set_tag t('Imputation'), class: %w(compact) do %>
		<%= f.select :activity_id, @activity.find_open.collect { |a| [a.description, a.id] }, include_blank: true %>
		<%= f.select :agency_id, @activity.year.agencies.collect { |a| [a.name, a.to_param] }, include_blank: true %>
		<%= f.select :budget_id, @activity.year.budgets.collect { |b| [b.account.name, b.to_param] } %>
	<% end %>

	<%= f.submit t('Create'), class: 'btn btn-primary pull-right' %>
<% end %>

app/views/activities/edit.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<%= form_for @activity, builder: BootstrapFormHorizontalBuilder, html: { class: %w(form-horizontal span5 well) } do |f| %>
			<%= field_set_tag t("form.#{controller.controller_name}.#{controller.action_name}"), class: %w(compact) do %>
				<%= f.text_field :description, placeholder: t('Name'), required: true %>
				<%= f.text_field :date, required: true, type: :date, value: l(f.object.date), class: :datepicker %>
				<%= f.text_field :plan_debit, type: :number, required: true %>
				<%= f.text_field :plan_credit, type: :number, required: true %>
				<%= f.select :agency_id, options_for_select(Agency.all.collect { |a| [a.name, a.id] }, @me.agency.id), include_blank: true %>
				<%= f.select :year_id, options_for_select(Year.all.collect { |y| [y.year, y.id] }, Year.current.id), include_blank: true %>
				<%= f.submit t("form.#{controller.action_name}"), class: %w(btn btn-primary pull-right) %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/activities/index.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span8 offset2">
			<% @agencies.each do |agency| %>
				<h3><%= @year.year %> &mdash; <%= agency.name %></h3>
				<table class="table table-bordered table-striped table-condensed">
					<thead>
					<tr>
						<th></th>
						<th><%= t('Activity') %></th>
						<th><%= t('Date') %></th>
						<th><%= t('Debit') %></th>
						<th><%= t('Credit') %></th>
						<th><%= t('Total') %></th>
						<th><%= t('%') %></th>
					</tr>
					</thead>
					<tbody>
					<%
					   Activity.where(year_id: @year, agency_id: agency).order('date').each do |activity| %>
						<%= content_tag :tr, class: activity.closed? ? :closed : nil do %>
							<td>
								<% if activity.closed? %>
									<%= image_tag 'empty.png', title: t('Closed activity'), class: 'sprite-silk-lock' %>
								<% end %>
							</td>
							<td><%= activity.description %></td>
							<td><%= l activity.date %></td>
							<td class="debit"><%= number_to_currency activity.debit %></td>
							<td class="credit"><%= number_to_currency activity.credit %></td>
							<%= content_tag :td, number_to_currency(activity.total), class: activity.total < 0 ? 'debit' : 'credit' %>
							<%= content_tag :td, activity_progress_bar(activity.percentage) %>
						<% end
						   end %>
					</tbody>
				</table>
			<% end %>
		</div>
	</div>
</div>

app/views/activities/new.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<%= form_for @activity, builder: BootstrapFormHorizontalBuilder, html: { class: %w(form-horizontal span5 well) } do |f| %>
			<%= field_set_tag t("form.#{controller.controller_name}.#{controller.action_name}"), class: %w(compact) do %>
				<%= f.text_field :description, placeholder: t('Name'), required: true %>
				<%= f.text_field :date, required: true, type: :date, value: l(f.object.date), class: %w(datepicker) %>
				<%= f.text_field :plan_debit, type: :number, required: true %>
				<%= f.text_field :plan_credit, type: :number, required: true %>
				<%= f.select :agency_id, options_for_select(Agency.all.collect { |a| [a.name, a.id] }, @me.agency.id), include_blank: true %>
				<%= f.select :year_id, options_for_select(Year.all.collect { |y| [y.year, y.id] }, Year.current.id), include_blank: true %>
				<%= f.submit t("form.#{controller.action_name}"), class: %w(btn btn-primary pull-right) %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/activities/show.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span10">
			<h3>
				<%= l @activity.date %> - <%= @activity.description %>
				<%= link_to [:edit, @activity] do
					image_tag 'empty.png', title: t('Edit activity'), class: 'sprite-silk-date_edit'
				end %>
				<% unless @activity.closed? %>
					<%= link_to close_activity_path(@activity), data: { confirm: t('Are you sure you want to close this activity ?') } do
						image_tag 'empty.png', title: t('Close activity'), class: 'sprite-silk-lock_open'
					end %>
				<% else %>
					<%= link_to close_activity_path(@activity), data: { confirm: t('Are you sure you want to activate this activity ?') } do
						image_tag 'empty.png', title: t('Activate activity'), class: 'sprite-silk-lock'
					end %>
				<% end %>
			</h3>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<div class="container-fluid">
				<div class="row-fluid">
					<h3><%= t('Entries') %></h3>
				</div>
				<table class="table table-bordered table-condensed row-fluid">
					<thead>
					<tr>
						<th></th>
						<th><%= t('Date') %></th>
						<th><%= t('Object') %></th>
						<th><%= t('Description') %></th>
						<th><%= t('Amount') %></th>
						<th><%= t('Type') %></th>
					</tr>
					</thead>
					<tbody>
					<% @activity.entries.sort_by(&:date).each do |e| %>
						<tr>
							<th>
								<%= link_to [:edit, e] do
									image_tag 'empty.png', title: t('Edit entry'), class: 'sprite-silk-coins_edit'
								end %>
								<%= link_to e, method: :delete, data: { confirm: t('Are you sure you want to delete this entry ?') } do
									image_tag 'empty.png', title: t('Delete entry'), class: 'sprite-silk-coins_delete'
								end %>
							</th>
							<td><%= l e.date %> </td>
							<td><%= e.to %> </td>
							<td><%= e.description %> </td>
							<%= content_tag :td, number_to_currency(e.amount), class: e.debit? ? 'debit' : 'credit' %>
							<td><%= t e.category %></td>
						</tr>
					<% end %>
					</tbody>
				</table>
			</div>
		</div>
		<div class="span6">
			<div class="container-fluid">
				<table class="table table-bordered table-condensed row-fluid">
					<thead>
					<tr>
						<th></th>
						<th><%= t('Debit') %></th>
						<th><%= t('Credit') %></th>
						<th><%= t('Total') %></th>
						<th>%</th>
					</tr>
					</thead>
					<tbody>
					<tr>
						<th><%= t('Planned') %></th>
						<td><%= number_to_currency @activity.plan_debit %></td>
						<td><%= number_to_currency @activity.plan_credit %></td>
						<td><%= number_to_currency @activity.plan_total %></td>
						<%= content_tag :td, activity_progress_bar(@activity.plan_percentage) %>
					</tr>
					<tr>
						<th><%= t('Realized') %></th>
						<td><%= number_to_currency @activity.debit %></td>
						<td><%= number_to_currency @activity.credit %></td>
						<td><%= number_to_currency @activity.total %></td>
						<%= content_tag :td, activity_progress_bar(@activity.percentage) %>
					</tr>
					</tbody>
				</table>
				<div class="row-fluid">
					<%= render 'entries/entry', entry: @entry, action: :new %>
				</div>
			</div>
		</div>
	</div>
</div>