config/routes.rb
GestionCe::Application.routes.draw do
	get 'login' => 'site#login'
	post 'login' => 'site#auth'
	get 'logout' => 'site#logout'

	get 'admin' => 'site#admin'
	get 'report' => 'site#report'
	get 'balance' => 'site#balance'

	resources :users
	resources :years
	resources :agencies
	resources :activities do
		member do
			get :close
		end
	end
	resources :entries
	resources :payments

	root to: 'site#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	around_filter :wrap_in_transaction
	before_filter :require_login

	def wrap_in_transaction
		ActiveRecord::Base.transaction do
			yield
		end
	end

	def require_login
		if session[:me]
			@me = User.find session[:me]
		else
			flash[:error] = 'Authentification nécessaire'
			redirect_to login_path
		end
	end

	def year
		year = params[:year]
		year.nil? ? Year.current : Year.find_by_year(year)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def progress_bar percentage, lvl1 = 25, lvl2 = 50, opts = {}
		classes = %w(bar-danger bar-warning bar-success)
		color = if opts[:inverse]
					if percentage <= lvl1
						classes[2]
					elsif percentage <= lvl2
						classes[1]
					else
						classes[0]
					end
				else
					if percentage < lvl1
						classes[0]
					elsif percentage < lvl2
						classes[1]
					else
						classes[2]
					end
				end
		content_tag :div, class: %w(progress progress-striped) do
			content_tag :div, number_to_percentage(percentage, precision: 0),
						class: ['bar', color], style: "width: #{percentage.round}%;"
		end
	end
end

app/views/application/_errors.html.erb
<% if object && object.errors.any? %>
	<div class="row">
		<div class="alert alert-error span6 offset3">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<strong><%= pluralize object.errors.count, 'error' %> prohibited
				this <%= object.class.to_s.downcase %> from being saved :</strong>
			<ul>
				<% object.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/application/_flashs.html.erb
<div id="flash" class="container">
	<% [:error, :warning, :success, :info].each do |level|
		if flash[level] %>
			<%= content_tag :div, class: %(alert alert-#{level} fade in) do %>
				<%= button_tag 'x', type: 'button', class: 'close', data: { dismiss: 'alert' } %>
				<%= flash[level] %>
			<% end
		end
	end %>
</div>

app/views/application/_headers.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to root_path, class: %w(brand) do %>
				<i class="icon-lock"></i>
				Gestion CE
			<% end %>
			<div>
				<ul class="nav">
					<li>
						<%= link_to admin_path, class: %w(navbar-link) do %>
							<i class="icon-cog"></i>
							<%= t 'Admin' %>
						<% end %>
					</li>
				</ul>
				<% if @me %>
					<ul class="nav pull-right">
						<li>
							<%= link_to logout_path, class: %w(navbar-link) do %>
								<i class="icon-signout"></i>
								<%= t 'Sign out' %>
							<% end %>
						</li>
						<li>
							<a>
								<i class="icon-user"></i>
								~<%= @me.login %>
							</a>
						</li>
					</ul>
				<% else %>
					<ul class="nav pull-right">
						<li>
							<a href="#modal-login" data-toggle="modal" class="navbar-link">
								<i class="icon-signin"></i>
								<%= t 'Sign in' %>
							</a>
						</li>
					</ul>
				<% end %>
			</div>
		</div>
	</div>
</header>